### ISSUE TITLE
Minify the files on the save

### ISSUE THREAD

**Issue by nunoguerra** [mjvotaw/Coda-2-JS-Minify#1]
Hi

What do you think about minify the files on the save?

We can editing the script.js and on save the plugin generate script.min.js

I think it's a good idea! Let me know what you think about it.

Cheers

**Comment by mjvotaw** [comment]
Perhaps I'm not quite understanding you, but are you asking for a plugin that minifies any javascript file on save, without any setup, as this plugin requires?

**Comment by nunoguerra** [comment]
My idea is: Editing the JS file on server and when you save, the plugin generate a minify version and put it on the same folder of your file edited.

**Comment by mjvotaw** [comment]
If you're talking about editing a file on a remote server, I don't think that's a possibility. But for local files, that's exactly what this plugin does. If you're having trouble getting the plugin to work, take a look at the "How do you use it" section of the readme ( https://github.com/mjvotaw/Coda-2-JS-Minify#how-do-you-use-it ).

**Comment by nunoguerra** [comment]
I know how the plugin works.

My question is, if exist the possibility to make the minify on save editing file on remote server.

Thanks.

**Comment by mjvotaw** [comment]
No problem.
You're not the first person to ask for that functionality, actually, but unfortunately I don't think it's possible :/

**Comment by fabiocaccamo** [comment]
+1 for this request :(

**Comment by mjvotaw** [comment]
This kind of isn't a matter of me not wanting to do it, or of Coda not giving me the ability to do so through a plugin. Editing a remote file isn't like editing something locally. When you edit a remote file, Coda makes a temporary copy of the file on your local machine and then uploads it to the remote server when you save. I don't have that ability as a plugin writer.

Frankly, I personally wouldn't feel comfortable writing a plugin that automatically creates and uploads a file to a remote server. I'm of the opinion that you should avoid directly editing remote files whenever possible, and instead work on changes locally before pushing them.
