### ISSUE TITLE
how to minify?

### ISSUE THREAD

**Issue by mrbbp** [mjvotaw/Coda-2-JS-Minify#3]
ok i should be super stupid but I've read the "tut" and adjust settings and prefs and so?
nothing happen !
how to start minify?

regards

**Comment by mjvotaw** [comment]
Hi,

Can you post the output from the plugin here?
- First, make sure to turn on Verbose Logging in the plugin's preferences
- Open the Console application
- Try to minify a file
- Copy any lines that start with "JS Minify:"

Can you also tell me, what version of Coda and OS X you're using?

**Comment by mrbbp** [comment]
how to do that : "Try to minify a file"?
click on what? which button?

**Comment by mjvotaw** [comment]
Ahh, I understand your confusion now, sorry.
If you have everything setup right, the plugin will create a minified version of the js file when you save.
So if you have main.js added to the Site Settings, when you save, there should be a main.min.js file created in the same directory.

**Comment by TomReddish-MVC** [comment]
When I saved it the first time it created the .min file but I changed some settings around (got rid of comments) and now it's not updating the file when I save.
