### ISSUE TITLE
Site setting menu is not available.

### ISSUE THREAD

**Issue by urlless** [mjvotaw/Coda-2-JS-Minify#4]
Hi, I really hope to use your plugin.
but Site Setting menu is not available.

![screen shot 2016-07-10 at 7 24 38 am](https://cloud.githubusercontent.com/assets/11046516/16710609/9aca6b32-466f-11e6-8760-2e8b3a6729e0.png)

Would you let me know the reason?
Thanks.

OS X 10.11 / Coda 2.5.16

**Comment by mjvotaw** [comment]
Hi urlless,
The only reason that the Site Settings should be disabled is if you don't have a Site opened in Coda. Less files are stored unique to each Site.

**Comment by urlless** [comment]
Thank so much! It works!
